version: "3.6"

services:
  nginx:
    build:
      context: ./dockerfiles/nginx
      dockerfile: Dockerfile
      args:
        SERVERROOT: public
        SERVERNAME: localhost
    volumes:
      - nginx-ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql:
    build:
      context: ./dockerfiles/mysql
      dockerfile: Dockerfile
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: password
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  php-fpm:
    build:
      context: .
      dockerfile: ./dockerfiles/phpfpm/Dockerfile
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:

volumes:
  mysql-data:
    driver_opts:
      type: volume
      device: /var/lib/mysql
      o: bind
  nginx-ssl:
    driver_opts:
      type: volume
      device: /etc/nginx/ssl
      o: bind